services:
  wls-proxy:
    build:
      context: ./
      dockerfile: ./wls-proxy/Dockerfile
    networks:
      - web
    environment:
      - VIRTUAL_HOST=wls.byleo.net
      - LETSENCRYPT_HOST=wls.byleo.net
      - VIRTUAL_PORT=80
    restart: always
    depends_on:
      - wls-backend

  wls-backend:
    build: ./wls-backend
    networks:
      - web
    expose:
      - 8080
    volumes:
      - ./wls-backend/wl-stoerungsarchiv-firebase-adminsdk.json:/run/wl-stoerungsarchiv-firebase-adminsdk.json:ro
    environment:
      - Db__Host=wls-db
      - Db__User=postgres
      - Db__Password=schueler
      - GOOGLE_APPLICATION_CREDENTIALS=/run/wl-stoerungsarchiv-firebase-adminsdk.json
    restart: always
    depends_on:
      - wls-db

  wls-db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=schueler
    networks:
      - web
    expose:
      - 5432

networks:
  web:
    external: true
