// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wls_backend.Data;

#nullable disable

namespace wls_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826110800_UpdateDatabaseStructure")]
    partial class UpdateDatabaseStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisturbanceLine", b =>
                {
                    b.Property<string>("DisturbancesId")
                        .HasColumnType("text");

                    b.Property<string>("LinesId")
                        .HasColumnType("text");

                    b.HasKey("DisturbancesId", "LinesId");

                    b.HasIndex("LinesId");

                    b.ToTable("DisturbanceLine");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Disturbance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Disturbance");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.DisturbanceDescription", b =>
                {
                    b.Property<string>("DisturbanceId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DisturbanceId", "Text", "CreatedAt");

                    b.ToTable("DisturbanceDescription");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Line", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Subscription", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("LineId")
                        .HasColumnType("text");

                    b.HasKey("DeviceId", "LineId");

                    b.HasIndex("LineId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("DisturbanceLine", b =>
                {
                    b.HasOne("wls_backend.Models.Domain.Disturbance", null)
                        .WithMany()
                        .HasForeignKey("DisturbancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wls_backend.Models.Domain.Line", null)
                        .WithMany()
                        .HasForeignKey("LinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wls_backend.Models.Domain.DisturbanceDescription", b =>
                {
                    b.HasOne("wls_backend.Models.Domain.Disturbance", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("DisturbanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Subscription", b =>
                {
                    b.HasOne("wls_backend.Models.Domain.Device", "Device")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wls_backend.Models.Domain.Line", "Line")
                        .WithMany("Subscriptions")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Device", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Disturbance", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("wls_backend.Models.Domain.Line", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
